"""
Type stubs for the JIT environment.

This module provides type annotations for all JIT‑exposed variables and
functions. It is intended to be imported conditionally (e.g., under
`if TYPE_CHECKING:`) to satisfy linters and IDEs without affecting
runtime behaviour or the AST traversal performed by the JIT compiler.

Because the JIT generator only inspects the function body, imports from
this module are safe and will not be inlined into the generated shader.
"""

from typing import List, Tuple, Any, TYPE_CHECKING

# ---- Built‑in variables for object scripts ----
x: float
y: float
vx: float
vy: float
mass: float
charge: float
theta: float
omega: float
ax: float
ay: float
angular: float

# ---- Paint script variables ----
px: float
py: float
prev_r: float
prev_g: float
prev_b: float
prev_a: float
color: Tuple[float, float, float, float]

# ---- Agent script variables ----
signal_object_idx: int
signal_payload: float

# ---- Common constants ----
num_objects: int
dt: float
time: float
idx: int
group_count: int
i: int

# ---- Object array p ----
class _Object:
    x: float
    y: float
    vx: float
    vy: float
    mass: float
    charge: float
    theta: float
    omega: float
    r: float
    g: float
    b: float
    a: float
    # Additional fields if needed
p: List[_Object]

# ---- JIT‑exposed math functions ----
def sqrt(x: float) -> float: ...
def sin(x: float) -> float: ...
def cos(x: float) -> float: ...
def tan(x: float) -> float: ...
def exp(x: float) -> float: ...
def log(x: float) -> float: ...
def pow(x: float, y: float) -> float: ...
def abs(x: float) -> float: ...
def floor(x: float) -> float: ...
def ceil(x: float) -> float: ...
def fract(x: float) -> float: ...
def mod(x: float, y: float) -> float: ...
def min(x: float, y: float) -> float: ...
def max(x: float, y: float) -> float: ...
def clamp(x: float, min_val: float, max_val: float) -> float: ...
def length(v: Tuple[float, ...]) -> float: ...
def dot(a: Tuple[float, ...], b: Tuple[float, ...]) -> float: ...
def cross(a: Tuple[float, float, float], b: Tuple[float, float, float]) -> Tuple[float, float, float]: ...
def normalize(v: Tuple[float, ...]) -> Tuple[float, ...]: ...
def reflect(inc: Tuple[float, ...], normal: Tuple[float, ...]) -> Tuple[float, ...]: ...
def refract(inc: Tuple[float, ...], normal: Tuple[float, ...], eta: float) -> Tuple[float, ...]: ...
def atan2(y: float, x: float) -> float: ...
def atan(x: float) -> float: ...
def asin(x: float) -> float: ...
def acos(x: float) -> float: ...
def sinh(x: float) -> float: ...
def cosh(x: float) -> float: ...
def tanh(x: float) -> float: ...
def radians(deg: float) -> float: ...
def degrees(rad: float) -> float: ...
def saturate(x: float) -> float: ...
def lerp(a: float, b: float, t: float) -> float: ...
def fbm(p: Tuple[float, float], octaves: int) -> float: ...
def noise(p: Tuple[float, float]) -> float: ...
def rand() -> float: ...  # seedless random

# ---- JIT‑specific API ----
def signal(agent_id: int, payload: float) -> None: ...
def scratchpad_read(id: int, index: int) -> float: ...
def scratchpad_write(id: int, index: int, value: float) -> None: ...
def apply_constraints() -> None: ...
def detect_collision(other: int) -> bool: ...
def resolve_collision(other: int) -> None: ...

# ---- Ray‑tracing structs (if used) ----
class Ray:
    origin: Tuple[float, float, float]
    direction: Tuple[float, float, float]

class Hit:
    hit: bool
    t: float
    point: Tuple[float, float, float]
    normal: Tuple[float, float, float]
    uv: Tuple[float, float]
    material: int

class GeoObject: ...
class CameraBasis: ...

def camera_ray(eye: Tuple[float, float, float],
               target: Tuple[float, float, float],
               up: Tuple[float, float, float],
               fov: float) -> Ray: ...
def intersect(ray: Ray, obj: Any) -> Hit: ...
def miss_hit() -> Hit: ...
def closest_hit(a: Hit, b: Hit) -> Hit: ...

# Expose all symbols for `from typed import *`
__all__ = [
    'x', 'y', 'vx', 'vy', 'mass', 'charge', 'theta', 'omega',
    'ax', 'ay', 'angular',
    'px', 'py', 'prev_r', 'prev_g', 'prev_b', 'prev_a', 'color',
    'signal_object_idx', 'signal_payload',
    'num_objects', 'dt', 'time', 'idx', 'group_count', 'i',
    'p',
    'sqrt', 'sin', 'cos', 'tan', 'exp', 'log', 'pow', 'abs',
    'floor', 'ceil', 'fract', 'mod', 'min', 'max', 'clamp',
    'length', 'dot', 'cross', 'normalize', 'reflect', 'refract',
    'atan2', 'atan', 'asin', 'acos', 'sinh', 'cosh', 'tanh',
    'radians', 'degrees', 'saturate', 'lerp', 'fbm', 'noise', 'rand',
    'signal', 'scratchpad_read', 'scratchpad_write',
    'apply_constraints', 'detect_collision', 'resolve_collision',
    'Ray', 'Hit', 'GeoObject', 'CameraBasis',
    'camera_ray', 'intersect', 'miss_hit', 'closest_hit',
]